version: "3"

services:
  nginx-rtmp:
    build: .
    restart: always
    ports:
      - ${RTMP_PORT}:1935
      - ${HTTP_PORT}:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    env_file:
      - .env
    volumes:
      - ./certs:/opt/certs
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf.template
